local keymap_default = keymap_new(0)
keymap_bind(keymap_default, "left", function(context) mark_move(context.cursor, -1) end)
keymap_bind(keymap_default, "right", function(context) mark_move(context.cursor, 1) end)
keymap_bind(keymap_default, "up", function(context) mark_set(bline_get_prev(context.bline), context.tcol) end)
keymap_bind(keymap_default, "down", function(context) mark_set(bline_get_next(context.bline), context.tcol) end)
keymap_bind(keymap_default, "home", function(context) mark_set(context.bline, 0) end)
keymap_bind(keymap_default, "Ca", function(context) mark_set(context.bline, 0) end)
keymap_bind(keymap_default, "end", function(context) mark_set(context.bline, bline_get_length(context.bline) - 1) end)
keymap_bind(keymap_default, "Ce", function(context) mark_set(context.bline, bline_get_length(context.bline) - 1) end)
keymap_bind_default(keymap_default, function(context)
    ok, offset, line, col = buffer_insert(context.buffer, context.col, context.keyc, string.len(context.keyc))
    atto_debug(string.format("offset=%d line=%d col=%d", offset, line, col))
end)

bview_keymap_push(bview_edit, keymap_default)
bview_keymap_push(bview_prompt, keymap_default)
